services:
  frontend:
      build:
        context: .
        dockerfile: Dockerfile.frontend
      ports:
        - "5173:5173"
      environment:
        - NODE_ENV=production
        - VITE_BACKEND_URL=http://backend:3000
      volumes:
        - ./client:/app/client
        - /app/node_modules
      networks:
        - app-network
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    volumes:
      - ./downloads:/app/downloads:rw   # Keep this if you need persistent storage for downloads
    networks:
      - app-network

networks:
  app-network:
    driver: bridge